var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":59,"id":4541,"methods":[{"el":42,"sc":2,"sl":29},{"el":57,"sc":2,"sl":44}],"name":"SubjectTypeSpec","sl":27}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_110":{"methods":[{"sl":29}],"name":"Verify that authorization_authority has bytevalue 2","pass":true,"statements":[{"sl":32},{"sl":33}]},"test_134":{"methods":[{"sl":44}],"name":"Verify that SubjectType.getByValue returns root_ca for 4","pass":true,"statements":[{"sl":47}]},"test_14":{"methods":[{"sl":29}],"name":"Verify that crl_signer has bytevalue 5","pass":true,"statements":[{"sl":32},{"sl":33}]},"test_162":{"methods":[{"sl":29}],"name":"Verify that enrollment_credential has bytevalue 0","pass":true,"statements":[{"sl":32},{"sl":33}]},"test_172":{"methods":[{"sl":29}],"name":"Verify that root_ca has bytevalue 4","pass":true,"statements":[{"sl":32},{"sl":33}]},"test_264":{"methods":[{"sl":44}],"name":"Verify that SubjectType.getByValue returns authorization_ticket for 1","pass":true,"statements":[{"sl":47}]},"test_29":{"methods":[{"sl":44}],"name":"Verify that SubjectType.getByValue returns enrollment_credential for 0","pass":true,"statements":[{"sl":47}]},"test_309":{"methods":[{"sl":44}],"name":"Verify that SubjectType.getByValue returns enrollment_authority for 3","pass":true,"statements":[{"sl":47}]},"test_352":{"methods":[{"sl":29}],"name":"Verify that authorization_ticket has bytevalue 1","pass":true,"statements":[{"sl":32},{"sl":33}]},"test_362":{"methods":[{"sl":29}],"name":"Verify that enrollment_authority has bytevalue 3","pass":true,"statements":[{"sl":32},{"sl":33}]},"test_381":{"methods":[{"sl":44}],"name":"Verify that SubjectType.getByValue returns authorization_authority for 2","pass":true,"statements":[{"sl":47}]},"test_46":{"methods":[{"sl":44}],"name":"Verify that SubjectType.getByValue returns crl_signer for 5","pass":true,"statements":[{"sl":47}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [362, 352, 14, 172, 110, 162], [], [], [362, 352, 14, 172, 110, 162], [362, 352, 14, 172, 110, 162], [], [], [], [], [], [], [], [], [], [], [29, 381, 46, 134, 309, 264], [], [], [29, 381, 46, 134, 309, 264], [], [], [], [], [], [], [], [], [], [], [], []]
