var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":68,"id":3915,"methods":[{"el":48,"sc":2,"sl":31},{"el":66,"sc":2,"sl":50}],"name":"HeaderFieldTypeSpec","sl":29}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_103":{"methods":[{"sl":31}],"name":"Verify that generation_time_confidence has bytevalue 1","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_123":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns expiration for 2","pass":true,"statements":[{"sl":53}]},"test_124":{"methods":[{"sl":31}],"name":"Verify that generation_time has bytevalue 0","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_152":{"methods":[{"sl":31}],"name":"Verify that request_unrecognized_certificate has bytevalue 4","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_183":{"methods":[{"sl":31}],"name":"Verify that generation_location has bytevalue 3","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_234":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns generation_time for 0","pass":true,"statements":[{"sl":53}]},"test_260":{"methods":[{"sl":31}],"name":"Verify that expiration has bytevalue 2","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_289":{"methods":[{"sl":31}],"name":"Verify that signer_info has bytevalue 128","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_325":{"methods":[{"sl":31}],"name":"Verify that recipient_info has bytevalue 129","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_329":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns encryption_parameters for 130","pass":true,"statements":[{"sl":53}]},"test_347":{"methods":[{"sl":31}],"name":"Verify that encryption_parameters has bytevalue 130","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_35":{"methods":[{"sl":31}],"name":"Verify that message_type has bytevalue 5","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_371":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns signer_info for 128","pass":true,"statements":[{"sl":53}]},"test_390":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns request_unrecognized_certificate for 4","pass":true,"statements":[{"sl":53}]},"test_391":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns generation_time_confidence for 1","pass":true,"statements":[{"sl":53}]},"test_59":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns message_type for 5","pass":true,"statements":[{"sl":53}]},"test_88":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns generation_location for 3","pass":true,"statements":[{"sl":53}]},"test_97":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns recipient_info for 129","pass":true,"statements":[{"sl":53}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [260, 289, 347, 103, 152, 124, 35, 183, 325], [], [], [260, 289, 347, 103, 152, 124, 35, 183, 325], [260, 289, 347, 103, 152, 124, 35, 183, 325], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [391, 97, 88, 390, 329, 234, 123, 371, 59], [], [], [391, 97, 88, 390, 329, 234, 123, 371, 59], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
