var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":60,"id":5233,"methods":[{"el":44,"sc":2,"sl":31},{"el":58,"sc":2,"sl":46}],"name":"PayloadTypeSpec","sl":29}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_178":{"methods":[{"sl":46}],"name":"Verify that TrailerFieldType.getByValue returns signed for 1","pass":true,"statements":[{"sl":49}]},"test_229":{"methods":[{"sl":46}],"name":"Verify that TrailerFieldType.getByValue returns encrypted for 2","pass":true,"statements":[{"sl":49}]},"test_258":{"methods":[{"sl":31}],"name":"Verify that encrypted has bytevalue 2","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_345":{"methods":[{"sl":31}],"name":"Verify that unsecured has bytevalue 0","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_365":{"methods":[{"sl":46}],"name":"Verify that TrailerFieldType.getByValue returns signed_and_encrypted for 4","pass":true,"statements":[{"sl":49}]},"test_375":{"methods":[{"sl":46}],"name":"Verify that TrailerFieldType.getByValue returns unsecured for 0","pass":true,"statements":[{"sl":49}]},"test_380":{"methods":[{"sl":31}],"name":"Verify that signed_external has bytevalue 3","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_53":{"methods":[{"sl":46}],"name":"Verify that TrailerFieldType.getByValue returns signed_external for 3","pass":true,"statements":[{"sl":49}]},"test_68":{"methods":[{"sl":31}],"name":"Verify that signed has bytevalue 1","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_80":{"methods":[{"sl":31}],"name":"Verify that signed_and_encrypted has bytevalue 4","pass":true,"statements":[{"sl":34},{"sl":35}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [380, 258, 345, 68, 80], [], [], [380, 258, 345, 68, 80], [380, 258, 345, 68, 80], [], [], [], [], [], [], [], [], [], [], [375, 229, 365, 178, 53], [], [], [375, 229, 365, 178, 53], [], [], [], [], [], [], [], [], [], [], []]
